name: Merge M8
author: Ewen MacCulloch <ewen@macculloch.net>
description: Merge M8 posts a concise, actionable report directly on the PR to accelerate resolution and reduce review thrash.
branding:
  color: gray-dark
  icon: upload-cloud

inputs:
  github_token:
    description: GitHub token with permissions to read PRs and post comments
    required: true
    default: ${{ github.token }}
  timeZone:
    description: Time zone for calculations (TZ format)
    required: false
    default: Australia/Sydney

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Install dependencies
      shell: bash
      run: |
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi

    - name: Run Nightwatch
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        TZ: ${{ inputs.timeZone }}
      run: |
        node lib/main.js
