name: Merge M8
author: Ewen MacCulloch <ewen@macculloch.net>
description: Merge M8 posts a concise, actionable report directly on the PR to accelerate resolution and reduce review thrash.
branding:
  color: gray-dark
  icon: upload-cloud

inputs:
  github_token:
    description: GitHub token with permissions to read PRs and post comments
    required: true
    default: ${{ github.token }}
  timeZone:
    description: Time zone for calculations (TZ format)
    required: false
    default: Australia/Sydney
  dangerousPatterns:
    description: |
      Optional YAML to override sensitive file patterns. If omitted, uses default patterns.
      Format:
        banned:
          - pattern: ^\.env$
            reason: Dotenv file
          - pattern: secrets?
            reason: Contains secrets
        allowed:
          - ^\.env\.example$
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Run Merge M8
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        TZ: ${{ inputs.timeZone }}
        DANGEROUS_PATTERNS: ${{ inputs.dangerousPatterns }}
      run: |
        node lib/main.js
